name: Update POT file

on:
  push:
    branches:
    - dev
    paths:
    - '**.php'
    - '**.js'

jobs:
  update-pot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update POT file
      uses: platform-coop-toolkit/action-wp-pot-generator@master
      with:
        save_path: './languages'
        item_slug: 'coop-library-framework'
        domain: 'coop-library-framework'
        package_name: 'Co-op Library Framework'
        headers: "{\"Report-Msgid-Bugs-To\":\"https://github.com/platform-coop-toolkit/coop-library-framework/issues\"}"
    - name: Commit updated POT file
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: 'chore(localization): update languages/coop-library-framework.pot'
